{{- with .Values.rollout }}
{{- if eq .strategy "canary" -}}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ template "name" $ }}-success-rate
spec:
  args:
    - name: service-name
  metrics:
    - name: success-rate
      interval: 1h
      successCondition: result[0] >= 5
      failureLimit: 3
      provider:
      prometheus:
          address: http://prometheus.linkerd.svc.cluster.local:9090
          timeout: 1
            query: |
              sum(
                rate(
                  response_total{
                    namespace="{{ $.Relese.namespace }}",
                    deployment=~"{{ target }}",
                    classification!="failure",
                    direction="inbound"
                  }[{{ interval }}]
                )
              ) 
              / 
              sum(
                rate(
                  response_total{
                    namespace="{{ $.Relese.namespace }}",
                    deployment=~"{{ target }}",
                    direction="inbound"
                  }[{{ interval }}]
                )
              )
{{- end }}
{{- end }}