{{- if gt (len .Values.hostnames) 0 -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "name" $ }}
spec:
  secretName: {{ include "name" $ }}-tls
  dnsNames: 
    {{- include "hostnames.list" .Values.hostnames | nindent 4 }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
{{- end }}