{{- if kindIs "map" .Values.hpa }}
{{- with .Values.hpa -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "name" $ }}
spec:
  scaleTargetRef:
    {{- if eq $.Values.rollout.strategy "canary" }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    {{- else }}
    apiVersion: apps/v1
    kind: Deployment
    {{- end }}
    name: {{ include "name" $ }}
  minReplicas: {{ .replicas.min }}
  maxReplicas: {{ .replicas.max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .cpuTarget }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .memoryTarget }}
{{- end }}
{{- end }}
