{{- if kindIs "map" $.Values.serviceMesh }}
{{- range .Values.ports }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "name" $ }}-{{ .name }}-l5d-header
spec: 
  headers:
    customRequestHeaders:
      l5d-dst-override: {{ printf "%s.%s.svc.cluster.local:%s" (include "name" $) $.Release.Namespace (toString .port) }}
---
{{- end }}
{{- end }}
