apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "name" $ }}
value: {{ .Values.priority }}
globalDefault: false
description: "Priority class for {{ include "name" $ }} deployment pods."
